improvement_suggestions = [
    "More real-life examples",
    "Slightly slower pace",
    "Additional practice time",
    "More interactive activities",
    "Extra Q&A time",
    "Group discussion opportunities",
    "Deeper topic coverage",
    "More visual aids",
    "Real-world connections",
    "Advance material sharing",
    "Hands-on practice",
    "More detailed slides",
    "Clearer key points",
    "Practical case studies",
    "Increased student interaction",
    "More time flexibility",
    "Extra explanation time",
    "More live examples",
    "Enhanced class notes",
    "Flexible discussion time",
    "Use of quizzes",
    "Recap key topics",
    "Short topic summaries",
    "Visual learning support",
    "Encourage peer feedback",
    "Mid-session breaks",
    "Extra learning tips",
    "More application tasks",
    "Time for reflection",
    "Concept reinforcement activities",
    "Practice-based learning",
    "Engaging warm-ups",
    "Expanded examples list",
    "Better time management",
    "More follow-up questions",
    "Add review sessions",
    "Pre-session overview",
    "Encourage more questions",
    "Conceptual clarity check",
    "Interactive group tasks",
    "Varied teaching styles",
    "Frequent recaps",
    "Improve transitions",
    "Visual recap slides",
    "More class interaction",
    "Realistic scenarios used",
    "Live feedback moments",
    "Relevant task focus",
    "Use real data",
    "Include success stories"
]
